# Generated by Django 3.0.3 on 2020-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='authorInfo',
            field=models.CharField(default='Old user', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='authorInfo',
            field=models.CharField(default='Old user', max_length=100),
            preserve_default=False,
        ),
    ]
